### ISSUE TITLE
有没有nativescript里面js调用原生Activity的办法

### ISSUE THREAD

**Issue by bright999** [NativeScriptCN/NativeScript-in-chinese#1]
大神，看了您的翻译，感觉确实牛逼！我想问您一下有没有nativescript里面js调用原生Activity的办法，最近想把nativescript集成到项目当中，所以有这个需求，请大神指点一下

**Comment by 1392324000** [comment]
如果想自己通过NS的应用层访问原生api，有两个前提：
1、你要熟悉原生功能的结构 比如名字和方法 也就是你要用的那个原生api在哪里 如何用
2、你要按照NS提供的标准（数据格式）与原生api进行数据通讯（包括访问和获取），这点有文档http://docs.nativescript.org/core-concepts/accessing-native-apis-with-javascript


至于翻译 因为官方文档更新的很多 建议直接用谷歌浏览器的翻译功能 不过有些词句要注意 毕竟机器翻译错误比较多




------------------ 原始邮件 ------------------
发件人: "bright999";<notifications@github.com>;
发送时间: 2017年9月13日(星期三) 中午1:52
收件人: "NativeScriptCN/NativeScript-in-chinese"<NativeScript-in-chinese@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [NativeScriptCN/NativeScript-in-chinese] 有没有nativescript里面js调用原生Activity的办法 (#1)




大神，看了您的翻译，感觉确实牛逼！我想问您一下有没有nativescript里面js调用原生Activity的办法，最近想把nativescript集成到项目当中，所以有这个需求，请大神指点一下

**Comment by bright999** [comment]
收到，谢谢指点，我试试先
